# Домашнее задание #1

Для начала вам понадобится импортировать модуль `numpy` как `np`

In [22]:
# Начните писать код тут
import numpy as np
import matplotlib.pyplot as plot

## Задача №1

Считайте (через `input`) 2 числа: <br>
`n` - размер `Numpy` вектора; <br>
`x` - координата элемента вектора, который должен быть равен `1`. Остальные должны быть равны `0`. <br>
Создайте вектор размера `n`, в котором все элементы равны `0`, кроме элемента с номером `x` - он равен `1`.


In [5]:
# Начните писать код тут
n, x = int(input()), int(input())
a = np.array([0]*n)
a[x] = 1
print(a)

8
2
[0 0 1 0 0 0 0 0]


## Задача №2

Считайте 3 числа: `n, m, s`. Создайте `Numpy` вектор, состоящий из чисел от `n` до `m` с шагом `s`.

In [7]:
# Начните писать код тут
n , m , s = int(input()), int(input()), int(input())
a = np.array([i for i in range(n, m + 1, s)])
print(a)

1
9
2
[1 3 5 7 9]


## Задача №3

Создайте матрицу `3х3` со значениями от `0` до `8`. Значения нужно сгенерировать.

In [21]:
# Начните писать код тут
a = np.array([i for i in range(9)]).reshape(3, 3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Задача №4

1. Создайте матрицу `4х4` со случайными значениями.
2. Найдите максимальное значение первой строки, минимальное - второй, среднее - третьей, сумму - четвертой.

In [30]:
# Начните писать код тут
import random
a = np.array([random.randint(0, 10) for i in range(16)]).reshape(4,4)
print(a)
print(max(a[0]))
print(min(a[1]))
print(sum(a[2])/4)
print(sum(a[3]))

[[ 4  1  8  2]
 [10  4  7 10]
 [ 3  6  6  0]
 [ 8  9 10  2]]
8
4
3.75
29


## Задача №5

Создайте диагональную матрицу `5х5`, все ненулевые элементы равны 5.

In [44]:
# Начните писать код тут
a = np.array([5]*5)
x = np.diag((a))
print(x)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]


## Задача №6

Создайте `Numpy` массив случайных чисел размерности `6х6х6` и найдите максимальное значение среди всех элементов.

In [68]:
# Начните писать код тут
import random
a1 = np.array([random.randint(0, 1001) for i in range(0, 36)]).reshape(6, 6)
a2 = np.array([random.randint(0, 1001) for i in range(0, 36)]).reshape(6, 6)
a3 = np.array([random.randint(0, 1001) for i in range(0, 36)]).reshape(6, 6)
a4 = np.array([random.randint(0, 1001) for i in range(0, 36)]).reshape(6, 6)
a5 = np.array([random.randint(0, 1001) for i in range(0, 36)]).reshape(6, 6)
a6 = np.array([random.randint(0, 1001) for i in range(0, 36)]).reshape(6, 6)

b = np.stack((a1, a2, a3, a4, a5, a6), axis=0)

print(b)
print(b.shape)
print(b.max(axis = (0, 1, 2)))

[[[ 88 923 812 825 343 626]
  [324 362 669 120 803 866]
  [962 387  36 704 642 591]
  [851 911 975 541 914 376]
  [793 143  74 322 136 220]
  [122 906 742 701 631 410]]

 [[110 270 485 538 702 394]
  [271 369 910  83 257 972]
  [969 248 112  49 808 571]
  [698 923 609 864 699 117]
  [569 746 609 680 787 889]
  [287 977 804 730  46 101]]

 [[799 375 546 789 660 450]
  [373 651 465 149 366 113]
  [937 417 562 473 737  39]
  [328 697 447 788 897 513]
  [317 773 980 925 687  95]
  [435 299 111 632 844 271]]

 [[495 647 741 927  74  90]
  [602 561 184 133 924 220]
  [239 404 716 615 519 375]
  [ 45 579 452 695 715  98]
  [468 826 340 230 741 607]
  [339 356 637 741 605 943]]

 [[675  27  42 708 204 610]
  [461 364 633 810 567 179]
  [803 917 994 971 216 243]
  [332 720 627 649 865 440]
  [762 826 896  77 620 576]
  [527 791 613 943 656 892]]

 [[122  44 668 819 836 223]
  [265 513 936 827 704  71]
  [419 424  64 440 829 897]
  [654 370 874 258 175 257]
  [742 325 197 406   0 394]
  [967 894

## Задача №7

Напишите функцию, которая принимает на вход 2 `Numpy` матрицы, проверяет, можно ли их перемножить, и если можно - то перемножает и возвращает транспонированную результирующую матрицу.

In [81]:
# Начните писать код тут
def vivod_matrix():
    n = int(input('Enter n: '))
    m = int(input('Enter m: '))
    a = np.array([0] * (n * m))
    for i in range(n * m):
        a[i] = int(input())
    a = a.reshape(n, m)
    print(a)
    return a

a1 = vivod_matrix()
a2 = vivod_matrix()
try:
    b = a1 @ a2
except ValueError:
    print('Ne mogu!')
else:
    print(b.T)

Enter n: 2
Enter m: 3
1
5
11
1
1
1
[[ 1  5 11]
 [ 1  1  1]]
Enter n: 1
Enter m: 5
1
2
3
4
5
[[1 2 3 4 5]]
Ne mogu!


## Задача №8

Эту задачу можете как запрограммировать, так и решить на листочке.

Но проще, конечно, **запрограммировать**.

Здесь вам придется заглянуть в ноутбук ["Функция одной переменной/Производная функции многих переменных"](./Derivative.ipynb) и убедиться, что вы поняли, как дифференцировать функцию многих переменных, а также в ноутбук ["Оптимизация функции одной и многих переменных"](./Optimization.ipynb) и убедиться, что вы поняли, как работает градиентный спуск. Если все-таки не поняли - пишите в [чат](https://t.me/joinchat/01_ttlSQj3hjZTg6), тегайте меня, `@leonidt`, пришлю вам что-нибудь в помощь.

Дана функция:

$$ f(x_1, x_2) = x_1^2 + 2x_2^2 + e^{x_1+x_2} $$

Найдите минимум данной функции, завершив вычисления при погрешности $$\varepsilon = 0.5 $$, выбрав в качестве начального приблежения точку `(0, 0)` и коэффициент шага $$ H=0.1. $$

In [34]:
# Начните писать код тут
eps = 0.05
H = 0.1
x, y = 0, 0

def z(x, y):
    return (x**2 + 2*y**2 + np.exp(x+y))

def dz_x(x, y):
    return (2*x + np.exp(x+y))

def dz_y(x, y):
    return (4*y + np.exp(x+y))

def gradient(a, b):
    return np.sqrt(dz_x(x, y)**2 + dz_y(x,y)**2)

while (gradient(x,y) > eps):
    x_1 = x - H * dz_x(x, y)
    y_1 = y - H * dz_y(x, y)
    x, y = x_1, y_1
    print(gradient(x, y))
print('Minimum f(x_1, x_2) = ', format(z(x_1, y_1), '.5f'), ' in point (',
      format(x_1, '.5f'), '; ', format(y_1, '.5f'), ')', sep='')


0.7471031979436978
0.44803515237221764
0.2957489789911293
0.20803831606890583
0.1516869046478578
0.11263658922386695
0.08438070588930488
0.06347888153324344
0.04785038414938228
Minimum f(x_1, x_2) = 0.77274 in point (-0.29387; -0.16133)
